# Generated by Django 6.0.7 on 2026-07-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('FOLLOW_UP', 'Follow-up'), ('CHEMOTHERAPY', 'Chemotherapy'), ('RADIATION', 'Radiation Therapy'), ('REVIEW', 'Review')], default='FOLLOW_UP', max_length=30),
        ),
    ]
