# Generated by Django 6.0.7 on 2026-08-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_appointment_appointment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_title', models.CharField(max_length=200)),
                ('record_type', models.CharField(choices=[('BLOOD_TEST', 'Blood Test'), ('CT_SCAN', 'CT Scan'), ('MRI_SCAN', 'MRI Scan'), ('BIOPSY', 'Biopsy'), ('X_RAY', 'X-Ray'), ('DIAGNOSIS', 'Diagnosis Report'), ('OTHER', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.patient')),
            ],
        ),
    ]
